project:
  type: website
  output-dir: docs

website:
  title: "Alan's Portfolio"
  navbar:
    left:
      - text: "Bio"
        href: index.html
      - text: "Projects"
        href: projects.html
